import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Added Manrope, Inter
import "./global.css";
import { cache } from 'react';

import GlobalContactSection from "../components/GlobalContactSection";
import Footer from "../components/Footer";
import Navbar, { AnnouncementBanner } from "../components/Navbar";
import CookieConsent from "../components/CookieConsent";
import { getStrapiURL } from "@/lib/strapi-helper";
import { getSolutions, getPlatform } from "@/lib/data";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

// Fetch global site settings from Strapi
const getGlobalSettings = cache(async () => {
  try {
    const url = getStrapiURL('/global?populate=*');
    const fetchOptions: RequestInit = {
      next: { revalidate: 3600 }
    };

    // In Node.js environment, handle SSL for staging (only if using HTTPS)
    if (typeof window === 'undefined' && url.includes('https://staging.servitiumcrm.com')) {
      const https = await import('https');
      const agent = new https.Agent({
        rejectUnauthorized: false
      });
      // @ts-ignore - Node.js fetch accepts agent
      fetchOptions.agent = agent;
    }

    const res = await fetch(url, fetchOptions);
    if (!res.ok) {
      console.warn(`Failed to fetch global settings: ${res.status} ${res.statusText}`);
      return {};
    }
    const data = await res.json();
    return data.data || {};
  } catch (error) {
    console.warn("Could not fetch global settings:", error);
    return {};
  }
});

export async function generateMetadata(): Promise<Metadata> {
  const global = await getGlobalSettings();

  return {
    title: global.siteTitle || "ServitiumCRM",
    description: global.siteDescription || "Generated by create next app",
    icons: [
      {
        rel: 'icon',
        url: '/favicon.png',
      },
    ],
  };
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const solutions = await getSolutions();
  const platformData = await getPlatform();

  return (
    <html lang="en">
      <body className={` ${inter.variable} antialiased`}>
        <AnnouncementBanner />
        <Navbar initialSolutions={solutions} initialPlatformData={platformData} />
        <main>
          {children}
          <GlobalContactSection />
        </main>
        <Footer initialSolutions={solutions} initialPlatformData={platformData} />
        <CookieConsent />
      </body>
    </html>
  );
}